### ISSUE TITLE
'About this Repository' contains misleading information.

### ISSUE THREAD

**Issue by MurzynJ** [OPCFoundation/UA-ModelCompiler#98]
The following write-up in README.md is misleading.

>## About this Repository ##
>This repository contains *sub-modules* for the Nodeset files, which are independently tracked. Please clone this repository as shown:
>```
>git clone https://github.com/OPCFoundation/UA-ModelCompiler --recursive
>```

The repository contains a submodule for the Stack, not for the Nodeset files. And if one doesn't have access to the member-only repository, the submodule update would not work because the path in .gitmodules points to the member-only repository:

```
[submodule "Stack"]
	path = Stack
	url = https://github.com/OPCF-Members/UA-.NETStandard-Prototypes.git
```

**Comment by opcfoundation-org** [comment]
Fixed

**Comment by MurzynJ** [comment]
Still there is a problem, that the public repository contains a submodule which points to the private repository. So cloning with --recursive option, as it's shown in the text would not work for someone who doesn't have access to the private repository. One would need to clone the main repo first, then replace the path in .gitmodules and then initialize the submodule.

**Comment by opcfoundation-org** [comment]
Submodules are such a headache....
The repo now references the public repo like it has on my machine for awhile.

**Comment by NothinRandom** [comment]
Hello.  So how does one properly clone this repo?  It looks like the issue still exists because the referenced submodule is 404 (made private again I guess?).

**Comment by opcfoundation-org** [comment]
The release process is complicated because draft/release candidate files are kept in a member only repository.  

It should build if you do not recursively fetch submodules on clone and then use [ModelCompiler Solution.sln](https://github.com/OPCFoundation/UA-ModelCompiler/blob/master/ModelCompiler%20Solution.sln).
